---
title: "Write up"
author: "Kyle Nessen"
format: html
editor: visual
---

## Abstract

Environmental reviews rely on current and abundant geospatial records of sensitive species. iNaturalist is the largest repository of such information, but it is hidden from users due to policy decisions. I propose that Esri and iNaturalist partner to make this data available to Esri users. In this exchange, Esri will receive exclusive access to a valuable data product for the Living Atlas, and iNaturalist will receive financial support to continue its mission.

## The Problem

Environmental review is a required step in all major development projects. This process involves identifying the proposed site, querying all nearby sensitive species occurrence records, and making determinations about what a survey is likely to encounter. Regulators review this work, and determine next steps based on what they find.

The issue with this approach, is that only a fraction of the available data is being used, and almost all of it is stale.

Services like GBIF do an excellent job of collecting the observations of scattered museums and herbaria, and purpose built databases like CNDDB offer top tier records of California's protected species. However, the production of these records are costly and time intensive. All of these repositories have backlogs, many going back years or decades. The pace of fresh data, those observations within the last three years, are woefully lacking behind. And when considered all together, those records are being far outpaced by modern tools that allow for anyone to record observations.

INaturalist is the world's largest community science project ever attempted. As of this writing, there are 158 *million* observations that are research grade. This means that approximately 2.9 million people have taken a photo of some wild organism, proposed an ID, and then had others in the community reach a consensus. In total, more than 434,000 unique species have been observed this way, many of which are protected by law.

As policy, iNaturalist *obscures* the location of any rare species. This means, the latitude and longitude are randomly shuffled within a 2 mile radius, making them useless for environmental review. The user has no ability to undo this process. At most, they can share the true location of their observations with any "trusted" user that asks. The consequence of this policy is that a vanishingly small minority of organizations (with great effort) have access to these records, thereby excluding the possibility of any widespread adoption, erasing the critical value of this information.

## A Solution

The environmental review I describe above, at its core, is a GIS exercise. Out of a 100 environmental reviews, 98 are done with Esri products. ArcGIS is far and away the dominant tool used in environmental consulting firms, nonprofits, and government agencies.

The Living Atlas, an ambitious project to collect our geospatial information in one place, is an ideal place to